services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongo-data: {}
